### ISSUE TITLE
Webpack startup fails with `TypeError: StatoscopeWebpackPlugin is not a constructor`

### ISSUE THREAD

**Issue by erichiller** [statoscope/statoscope#80]
**Describe the bug**

When trying to run `webpack` with `@statoscope/webpack-plugin` installed, it fails saying:

```
[webpack-cli] Failed to load 'C:\Users\eric\dev\src\github.com\erichiller\inventory\client\webpack.config.js' config
[webpack-cli] TypeError: StatoscopeWebpackPlugin is not a constructor
    at Object.<anonymous> (C:\Users\eric\dev\src\github.com\erichiller\inventory\client\webpack.config.js:157:9)
    at Module._compile (C:\Users\eric\dev\src\github.com\erichiller\inventory\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (C:\Users\eric\dev\src\github.com\erichiller\inventory\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WebpackCLI.tryRequireThenImport (C:\Users\eric\dev\src\github.com\erichiller\inventory\node_modules\webpack-cli\lib\webpack-cli.js:32:22)
    at loadConfig (C:\Users\eric\dev\src\github.com\erichiller\inventory\node_modules\webpack-cli\lib\webpack-cli.js:1536:38)
    at WebpackCLI.resolveConfig (C:\Users\eric\dev\src\github.com\erichiller\inventory\node_modules\webpack-cli\lib\webpack-cli.js:1639:44)
```

**To Reproduce**
1. Add package with `yarn add -D @statoscope/webpack-plugin`
2. Add to `webpack.js` config:
```js
const glob = require( 'glob' );
const StatoscopeWebpackPlugin = require( '@statoscope/webpack-plugin' );
```
and within `config.plugins`:
```js
  new StatoscopeWebpackPlugin( {
      saveStatsTo: 'stats/stats-[name]-[hash].json',
      additionalStats: glob.sync( 'stats/*.json' ),
  } )
```
3. Run any `webpack build`, etc
4. See error (above)

**Versions**:
 - Statoscope: 5.2.0
 - Webpack: 5.40.0

**Comment by smelukov** [comment]
Hello! Thanks for the issue.
Please try to import Statoscope like this:
```js
const StatoscopeWebpackPlugin = require( '@statoscope/webpack-plugin' ).default;
```

Is it work?

**Comment by erichiller** [comment]
That does work! Is that how I should be importing it then?

**Comment by smelukov** [comment]
Yes. Also, I fixed usage example at readme.
Thanks again ☺️
